"""withdrawal

Revision ID: 0426b77d2f81
Revises: 61a17a9e137e
Create Date: 2025-11-05 06:18:50.285247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0426b77d2f81'
down_revision = '61a17a9e137e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('account_email', sa.String(length=255), nullable=True))
        batch_op.drop_column('stripe_transfer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_transfer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('account_email')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('payout_method')

    # ### end Alembic commands ###
