"""show comments

Revision ID: 08de7a1cabf3
Revises: ce4e6a7c9047
Create Date: 2025-09-27 15:31:51.756249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08de7a1cabf3'
down_revision = 'ce4e6a7c9047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add show_comments column as nullable first
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_comments', sa.Boolean(), nullable=True))

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_comments', sa.Boolean(), nullable=True))
    
    # Update existing records to have show_comments = True
    op.execute("UPDATE blogs SET show_comments = true WHERE show_comments IS NULL")
    op.execute("UPDATE videos SET show_comments = true WHERE show_comments IS NULL")
    
    # Now make the columns NOT NULL
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.alter_column('show_comments', nullable=False)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('show_comments', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('show_comments')

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('show_comments')

    # ### end Alembic commands ###
