"""removed_login_user_id

Revision ID: 181bfa5b673f
Revises: 5dcb91dec156
Create Date: 2025-07-21 07:54:33.052987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181bfa5b673f'
down_revision = '5dcb91dec156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('users_login_user_id_key'), type_='unique')
        batch_op.drop_column('login_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_user_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('users_login_user_id_key'), ['login_user_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
