"""changes

Revision ID: 232004432efd
Revises: 0426b77d2f81
Create Date: 2025-11-05 08:57:36.469597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232004432efd'
down_revision = '0426b77d2f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paypal_accounts', schema=None) as batch_op:
        batch_op.alter_column('paypal_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paypal_accounts', schema=None) as batch_op:
        batch_op.alter_column('paypal_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
