"""empty message

Revision ID: 326024a7bdb8
Revises: 08de7a1cabf3
Create Date: 2025-10-03 07:25:32.701415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326024a7bdb8'
down_revision = '08de7a1cabf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_restricted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('age_restricted')

    # ### end Alembic commands ###
