"""location to blogs

Revision ID: 418b009c3021
Revises: e2781f3df82c
Create Date: 2025-10-05 20:05:16.600384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418b009c3021'
down_revision = 'e2781f3df82c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locations', sa.JSON(), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('locations')

    # ### end Alembic commands ###
