"""Add indexing

Revision ID: 66b9372bd8f6
Revises: 3a86306c708d
Create Date: 2025-08-06 07:55:19.807818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b9372bd8f6'
down_revision = '3a86306c708d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blogs_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_blogs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blogs_likes'), ['likes'], unique=False)
        batch_op.create_index(batch_op.f('ix_blogs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_blogs_views'), ['views'], unique=False)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_likes'), ['likes'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_views'), ['views'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_views'))
        batch_op.drop_index(batch_op.f('ix_videos_status'))
        batch_op.drop_index(batch_op.f('ix_videos_likes'))
        batch_op.drop_index(batch_op.f('ix_videos_created_at'))
        batch_op.drop_index(batch_op.f('ix_videos_archived'))

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blogs_views'))
        batch_op.drop_index(batch_op.f('ix_blogs_status'))
        batch_op.drop_index(batch_op.f('ix_blogs_likes'))
        batch_op.drop_index(batch_op.f('ix_blogs_created_at'))
        batch_op.drop_index(batch_op.f('ix_blogs_archived'))

    # ### end Alembic commands ###
