"""Video Scheduling

Revision ID: 66c9ba32dc26
Revises: c94ad1db4fad
Create Date: 2025-09-02 07:55:56.892572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c9ba32dc26'
down_revision = 'c94ad1db4fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_scheduled', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_videos_is_scheduled'), ['is_scheduled'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_scheduled_at'), ['scheduled_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_videos_is_scheduled'))
        batch_op.drop_column('is_scheduled')
        batch_op.drop_column('scheduled_at')

    # ### end Alembic commands ###
