"""brand tags and paid promo

Revision ID: 6c7d6c0c8129
Revises: 964bb6983051
Create Date: 2025-10-06 21:33:37.068224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c7d6c0c8129'
down_revision = '964bb6983051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_tags', postgresql.ARRAY(sa.String(length=250)), nullable=True))
        batch_op.add_column(sa.Column('paid_promotion', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('paid_promotion')
        batch_op.drop_column('brand_tags')

    # ### end Alembic commands ###
