"""Content Post Flow

Revision ID: 6eec62f8804e
Revises: 76ed74f25eeb
Create Date: 2025-08-23 09:06:29.319831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eec62f8804e'
down_revision = '76ed74f25eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reason_for_rejection', sa.String(length=1000), nullable=True))
        batch_op.create_index(batch_op.f('ix_blogs_is_draft'), ['is_draft'], unique=False)

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reason_for_rejection', sa.String(length=1000), nullable=True))
        batch_op.create_index(batch_op.f('ix_videos_is_draft'), ['is_draft'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_is_draft'))
        batch_op.drop_column('reason_for_rejection')
        batch_op.drop_column('is_draft')

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blogs_is_draft'))
        batch_op.drop_column('reason_for_rejection')
        batch_op.drop_column('is_draft')

    # ### end Alembic commands ###
