"""Stripe

Revision ID: 76ed74f25eeb
Revises: ba0bebcec838
Create Date: 2025-08-11 11:02:26.143297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ed74f25eeb'
down_revision = 'ba0bebcec838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('stripe_account_id', sa.String(length=255), nullable=False),
    sa.Column('account_status', sa.String(length=50), nullable=True),
    sa.Column('charges_enabled', sa.Boolean(), nullable=True),
    sa.Column('payouts_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id'),
    sa.UniqueConstraint('stripe_account_id')
    )
    op.create_table('withdrawal_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stripe_transfer_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawal_requests')
    op.drop_table('stripe_accounts')
    # ### end Alembic commands ###
