"""add is_hidden to blog comments

Revision ID: 780893bff777
Revises: f78508c91334
Create Date: 2025-11-18 13:06:38.437318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780893bff777'
down_revision = 'f78508c91334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False)
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('is_hidden')

    # ### end Alembic commands ###
