"""brand tags and paid promo

Revision ID: 964bb6983051
Revises: 418b009c3021
Create Date: 2025-10-06 15:15:27.675427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '964bb6983051'
down_revision = '418b009c3021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_tags', postgresql.ARRAY(sa.String(length=250)), nullable=True))
        batch_op.add_column(sa.Column('paid_promotion', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('paid_promotion')
        batch_op.drop_column('brand_tags')

    # ### end Alembic commands ###
