"""add login track

Revision ID: 9a77cb91c871
Revises: 2a5f41640dc1
Create Date: 2025-11-18 10:46:06.308119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a77cb91c871'
down_revision = '2a5f41640dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_ip', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_login_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_login_user_agent', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_user_agent')
        batch_op.drop_column('last_login_country')
        batch_op.drop_column('last_login_ip')

    # ### end Alembic commands ###
