"""add cascade delete

Revision ID: b1efbc8840d1
Revises: 27f223e79d5e
Create Date: 2025-11-28 11:25:19.030683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1efbc8840d1'
down_revision = '27f223e79d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('blogs_created_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comments_commented_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('comments_blog_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'blogs', ['blog_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['commented_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cpm_config', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('cpm_config_updated_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('creator_earnings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('creator_earnings_creator_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('followers_follower_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('followers_followed_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['followed_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['follower_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('paypal_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('paypal_accounts_creator_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('stripe_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('stripe_accounts_creator_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('video_comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('video_comments_video_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('video_comments_commented_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['commented_by'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'videos', ['video_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('video_watch_times', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('video_watch_times_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('video_watch_times_video_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'videos', ['video_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('videos_created_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('withdrawal_requests_creator_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('withdrawal_requests_creator_id_fkey'), 'users', ['creator_id'], ['id'])

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('videos_created_by_fkey'), 'users', ['created_by'], ['id'])

    with op.batch_alter_table('video_watch_times', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('video_watch_times_video_id_fkey'), 'videos', ['video_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('video_watch_times_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('video_comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('video_comments_commented_by_fkey'), 'users', ['commented_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('video_comments_video_id_fkey'), 'videos', ['video_id'], ['id'])

    with op.batch_alter_table('stripe_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('stripe_accounts_creator_id_fkey'), 'users', ['creator_id'], ['id'])

    with op.batch_alter_table('paypal_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('paypal_accounts_creator_id_fkey'), 'users', ['creator_id'], ['id'])

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('followers_followed_id_fkey'), 'users', ['followed_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('followers_follower_id_fkey'), 'users', ['follower_id'], ['id'])

    with op.batch_alter_table('creator_earnings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('creator_earnings_creator_id_fkey'), 'users', ['creator_id'], ['id'])

    with op.batch_alter_table('cpm_config', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cpm_config_updated_by_fkey'), 'users', ['updated_by'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comments_blog_id_fkey'), 'blogs', ['blog_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('comments_commented_by_fkey'), 'users', ['commented_by'], ['id'])

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('blogs_created_by_fkey'), 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###
