"""Creator Earnings

Revision ID: ba0bebcec838
Revises: c138833f0534
Create Date: 2025-08-09 09:58:20.217591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0bebcec838'
down_revision = 'c138833f0534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('watch_time_minutes', sa.Integer(), nullable=False),
    sa.Column('earnings', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('cpm_rate_used', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creator_earnings')
    # ### end Alembic commands ###
