"""Blog scheduling

Revision ID: c94ad1db4fad
Revises: 26fba2bc594c
Create Date: 2025-08-29 11:34:32.884779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94ad1db4fad'
down_revision = '26fba2bc594c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_scheduled', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_blogs_is_scheduled'), ['is_scheduled'], unique=False)
        batch_op.create_index(batch_op.f('ix_blogs_scheduled_at'), ['scheduled_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blogs_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_blogs_is_scheduled'))
        batch_op.drop_column('is_scheduled')
        batch_op.drop_column('scheduled_at')

    # ### end Alembic commands ###
