"""keywords

Revision ID: ce4e6a7c9047
Revises: 66c9ba32dc26
Create Date: 2025-09-18 07:38:04.112946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce4e6a7c9047'
down_revision = '66c9ba32dc26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', postgresql.ARRAY(sa.String(length=250)), nullable=True))

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', postgresql.ARRAY(sa.String(length=250)), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('keywords')

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('keywords')

    # ### end Alembic commands ###
