"""Add age_restricted and location to blogs

Revision ID: e2781f3df82c
Revises: b46c850b4c00
Create Date: 2025-10-04 19:34:49.248112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2781f3df82c'
down_revision = 'b46c850b4c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_restricted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('age_restricted')

    # ### end Alembic commands ###
