"""Added UploadSession model

Revision ID: ee13ef9497e2
Revises: 780893bff777
Create Date: 2025-11-19 06:23:12.612079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee13ef9497e2'
down_revision = '780893bff777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_sessions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tus_url', sa.String(length=500), nullable=True),
    sa.Column('temp_path', sa.String(length=500), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_sessions')
    # ### end Alembic commands ###
