"""Blogs_status

Revision ID: f0f2c4668e49
Revises: 181bfa5b673f
Create Date: 2025-07-22 07:40:24.467119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0f2c4668e49'
down_revision = '181bfa5b673f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the enum type first
    blogstatus_enum = postgresql.ENUM('DRAFT', 'PENDING_APPROVAL', 'PUBLISHED', 'REJECTED', name='blogstatus')
    blogstatus_enum.create(op.get_bind())
    
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('status', blogstatus_enum, nullable=True))
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('archived')
        batch_op.drop_column('status')
        batch_op.drop_column('image')

    # Drop the enum type
    op.execute('DROP TYPE blogstatus')

    # ### end Alembic commands ###
